backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "product"
    lable: "Product"
    folder: "content/product"
    slug: "{{slug}}"
    fields:
      - {lable: "Title", name: "title" , widget: "string"}
      - {lable: "Discription", name: "discription" ,widget: "markdown"}
      - {lable: "Image", name: "image" ,widget: "image"}
      - {lable: "Amount", name: "amount" , widget: "amount"}