backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "product"
    label: "Product"
    folder: "content/product"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Discription", name: "discription", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Amount", name: "amount", widget: "string"}
      - {label: "Categories" , name: "categories" , widget: "list"}
      - {label: "Aditional Images" , name: "galleryImages" , widget: "list" , summary: '{{fields.images}}' , field: {label: Image, name: images, widget: image}}